data = {
    "no": 1,
    "duvar_no": 1,
    "modül_adı": "buzdolabı",
    "modül_tipi": 3,
    "svg1": "",
    "kasa_tipi": 1,
    "eni": 75,
    "yükseklik": 230,
    "derinlik": 70,
    "x1": 0,
    "y1": 50,
    "z1": 0,
    "sol_yan": {
        "dahil": True,
        "adı": "sol yan",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 70,
        "boy": 230,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 2
    },
    "sağ_yan": {
        "dahil": True,
        "adı": "sağ_yan",
        "x_1": 73.2,
        "y_1": 0,
        "z_1": 0,
        "en": 70,
        "boy": 230,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 2
    },
    "üst": {
        "düz": {
            "dahil": True,
            "adı": "üst düz",
            "tip": 3,
            "x_1": 1.8,
            "y_1": 0,
            "z_1": 0,
            "en": 70,
            "boy": 71.4,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 1.8,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "dik_köşe": {
            "dahil": False,
            "adı": "dik_köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "sol_ön_gir": 0,
            "sağ_ön_gir": 0,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        },
        "açılı_köşe": {
            "dahil": False,
            "adı": "açılı köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "sol_ön_gir": 0,
            "sağ_ön_gir": 0,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        },
        "ön_kayıt": {
            "dahil": False,
            "adı": "üst ön kayıt",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        },
        "arka_kayıt": {
            "dahil": False,
            "adı": "üst arka kayıt",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        }
    },
    "alt": {
        "düz": {
            "dahil": False,
            "adı": "alt",
            "tip": 3,
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 0,
            "boy": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "alt_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "dik_köşe": {
            "dahil": False,
            "adı": "dik_köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "sol_ön_gir": 20,
            "sağ_ön_gir": 30,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        },
        "açılı_köşe": {
            "dahil": False,
            "adı": "açılı köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "sol_ön_gir": 20,
            "sağ_ön_gir": 30,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            'tip': 3
        }
    },
    "raf": {
        "dahil": False,
        "adı": "raf",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "adet": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "sol_gir": 0,
        "sağ_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        'tip': 3
    },
    "ark_kş": {
        "dahil": True,
        "adı": "arka kuşak",
        "x_1": 1.8,
        "y_1": 210,
        "z_1": 0,
        "en": 71.4,
        "boy": 15,
        "alt_mesafe": 20,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "kln_sol": {
        "dahil": False,
        "adı": "sol kapama",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 0,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "kln_sağ": {
        "dahil": False,
        "adı": "sağ kapama",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 0,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "arkalık": {
        "dahil": True,
        "adı": "arkalık",
        "x_1": 0.9,
        "y_1": 0.9,
        "z_1": 1.6,
        "en": 73.2,
        "boy": 53.19999999999999,
        "tip": 1,
        "fugası": 0.9,
        "yiv_genişliği": 1.1,
        "kanal_derinliği": 1.1,
        "gövde_fugası": 1.1,
        "malzeme": {
            "s": 0,
            "kod": 66,
            "adı": "Kar Beyaz",
            "boy": 366,
            "en": 183,
            "kalınlık": 0.8,
            "fiyat": 210,
            "stok": 10,
            "firma": 101,
            "desen": False,
            "image": "rgb(255,255,255)"
        },
        "arka_gir": 1.6,
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "pervaz_sağ": False,
    "pervaz_sol": False,
    "sabit_raf": {
        "dahil": True,
        "adı": "sabit_raf",
        "x_1": 1.8,
        "y_1": 54,
        "z_1": 0,
        "en": 70,
        "boy": 71.4,
        "adet": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "sol_gir": 0,
        "sağ_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "tip": 3
    },
    "kapak": {
        "dahil": True,
        "adı": "1.kapak ",
        "x_1": 0.15,
        "y_1": 0.5,
        "z_1": 70,
        "en": 37.35,
        "boy": 54.5,
        "adet": 2,
        "yönü": "dikey",
        "cam_kodu": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "kulp": {
            "dahil": True,
            "sol_m": 10,
            "üst_m": 10,
            "x_1": 10.15,
            "y_1": 10.5,
            "z_1": 70,
            "en": 1,
            "boy": 18,
            "yuk": 2,
            "model": 10,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "kapak2": {
        "dahil": True,
        "adı": "2.kapak",
        "x_1": 37.5,
        "y_1": 0.5,
        "z_1": 70,
        "en": 37.35,
        "boy": 54.5,
        "adet": 2,
        "yönü": "dikey",
        "cam_kodu": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "kulp": {
            "dahil": True,
            "sol_m": 10,
            "üst_m": 10,
            "x_1": 47.5,
            "y_1": 10.5,
            "z_1": 70,
            "en": 1,
            "boy": 18,
            "yuk": 2,
            "model": 10,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "baza": {
        "dahil": False,
        "adı": "arka_kuşak",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "arka_gir": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    }
}

altData = {
    "no": 1,
    "duvar_no": 1,
    "modül_adı": "alt 2 kapak",
    "modül_tipi": 1,
    "svg1": "",
    "svg_üst": "",
    "kasa_tipi": 2,
    "eni": 60,
    "yükseklik": 87,
    "derinlik": 58,
    "x1": 0,
    "y1": 193,
    "z1": 0,
    "sol_yan": {
        "dahil": True,
        "adı": "sol yan",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 58,
        "boy": 75.2,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 2
    },
    "sağyan": {
        "dahil": True,
        "adı": "sağ_yan",
        "x_1": 58.2,
        "y_1": 0,
        "z_1": 0,
        "en": 58,
        "boy": 75.2,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 2
    },
    "üst": {
        "düz": {
            "dahil": False,
            "adı": "üst",
            "tip": 3,
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 0,
            "boy": 0,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "dik_köşe": {
            "dahil": False,
            "adı": "dik_köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "solön_gir": 0,
            "sağön_gir": 0,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "açılı_köşe": {
            "dahil": False,
            "adı": "açılı köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "solön_gir": 0,
            "sağön_gir": 0,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "ön_kayıt": {
            "dahil": True,
            "adı": "üst ön kayıt",
            "x_1": 1.8,
            "y_1": 0,
            "z_1": 48,
            "en": 10,
            "boy": 56.4,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 1.8,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            "tip": 3
        },
        "arka_kayıt": {
            "dahil": True,
            "adı": "üst arka kayıt",
            "x_1": 1.8,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 56.4,
            "yön": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 1.8,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8,
            "tip": 3,
            "renk": "fill=\"green\""
        }
    },
    "alt": {
        "düz": {
            "dahil": True,
            "adı": "alt düz",
            "tip": 3,
            "x_1": 1.8,
            "y_1": 75.2,
            "z_1": 0,
            "en": 58,
            "boy": 56.4,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 1.8,
                "image": "rgb(255,255,255)"
            },
            "alt_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "dik_köşe": {
            "dahil": False,
            "adı": "dik_köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "solön_gir": 20,
            "sağön_gir": 30,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        },
        "açılı_köşe": {
            "dahil": False,
            "adı": "açılı köşe",
            "x_1": 0,
            "y_1": 0,
            "z_1": 0,
            "en": 10,
            "boy": 0,
            "yön": 0,
            "solön_gir": 20,
            "sağön_gir": 30,
            "köşe_açı": 90,
            "köşe_mesafesi": 0,
            "malzeme": {
                "mn": 0,
                "kn": 0,
                "adı": "66_Kar Beyaz",
                "kalınlık": 0,
                "image": "rgb(255,255,255)"
            },
            "üst_gir": 0,
            "ön_gir": 0,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_bant": 0.8,
            "arka_bant": 0.8,
            "sol_bant": 0.8,
            "sağ_bant": 0.8
        }
    },
    "raf": {
        "dahil": True,
        "adı": "raf",
        "x_1": 1.8,
        "y_1": 37.6,
        "z_1": 0,
        "en": 58,
        "boy": 56.4,
        "adet": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "sol_gir": 0,
        "sağ_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "tip": 3
    },
    "ark_kş": {
        "dahil": False,
        "adı": "arka kuşak",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 15,
        "boy": 0,
        "alt_mesafe": 20,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 0,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "kln_sol": {
        "dahil": False,
        "adı": "sol kapama",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 15,
        "boy": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 0,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "kln_sağ": {
        "dahil": False,
        "adı": "sağ kapama",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 0,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8
    },
    "arkalık": {
        "dahil": True,
        "adı": "arkalık",
        "x_1": 0.9,
        "y_1": 0.9,
        "z_1": 1.6,
        "en": 58.2,
        "boy": 75.2,
        "tipi": 1,
        "fugası": 0.9,
        "yiv_genişliği": 1.1,
        "kanal_derinliği": 1.1,
        "gövde_fugası": 1.1,
        "malzeme": {
            "s": 0,
            "kod": 66,
            "adı": "Kar Beyaz",
            "boy": 366,
            "en": 183,
            "kalınlık": 0.8,
            "fiyat": 210,
            "stok": 10,
            "firma": 101,
            "desen": False,
            "image": "rgb(255,255,255)"
        },
        "arka_gir": 1.6,
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "pervaz_sağ": False,
    "pervaz_sol": False,
    "sabit_raf": {
        "dahil": False,
        "adı": "sabit_raf",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "adet": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "ön_gir": 0,
        "arka_gir": 0,
        "sol_gir": 0,
        "sağ_gir": 0,
        "ön_bant": 0.8,
        "arka_bant": 0.8,
        "sol_bant": 0.8,
        "sağ_bant": 0.8
    },
    "kapak": {
        "dahil": True,
        "adı": "1.kapak ",
        "x_1": 0.15,
        "y_1": 0.5,
        "z_1": 58,
        "en": 29.85,
        "boy": 76.5,
        "adet": 2,
        "yönü": "dikey",
        "cam_kodu": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "kulp": {
            "dahil": True,
            "sol_m": 10,
            "üst_m": 10,
            "x_1": 10.15,
            "y_1": 10.5,
            "z_1": 58,
            "en": 1,
            "boy": 18,
            "yuk": 2,
            "model": 10,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "kapak2": {
        "dahil": True,
        "adı": "2.kapak",
        "x_1": 30,
        "y_1": 0.5,
        "z_1": 58,
        "en": 29.85,
        "boy": 76.5,
        "adet": 2,
        "yönü": "dikey",
        "cam_kodu": 0,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "kulp": {
            "dahil": True,
            "sol_m": 10,
            "üst_m": 10,
            "x_1": 40,
            "y_1": 10.5,
            "z_1": 58,
            "en": 1,
            "boy": 18,
            "yuk": 2,
            "model": 10,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "baza": {
        "dahil": True,
        "adı": "baza",
        "x_1": 0,
        "y_1": 77,
        "z_1": 53,
        "en": 60,
        "boy": 10,
        "arka_gir": 1,
        "malzeme": {
            "mn": 0,
            "kn": 0,
            "adı": "66_Kar Beyaz",
            "kalınlık": 1.8,
            "image": "rgb(255,255,255)"
        },
        "sol_gir": 0,
        "sağ_gir": 0,
        "üst_gir": 0,
        "alt_gir": 0,
        "sol_bant": 0.8,
        "sağ_bant": 0.8,
        "üst_bant": 0.8,
        "alt_bant": 0.8,
        "tip": 1
    },
    "ank": {
        "dahil": False,
        "adı": "buzdolabı",
        "marka": "arçelik",
        "x_1": 0,
        "y_1": 0,
        "z_1": 0,
        "en": 0,
        "boy": 0,
        "derinlik": 0,
        "model": 1
    },
    "tezgah": {
        "dahil": True,
        "düz": {
            "dahil": True,
            "adı": "tezgah",
            "tip": 3,
            "x_1": 0,
            "y_1": -3,
            "z_1": 0,
            "en": 61,
            "boy": 60,
            "malzeme": {
                "s": 0,
                "kod": 66,
                "adı": "Kar Beyaz",
                "kalınlık": 3,
                "fiyat": 210,
                "stok": 10,
                "firma": 101,
                "desen": False,
                "image": "rgb(200,200,200)"
            },
            "alt_gir": 0,
            "ön_gir": -3,
            "arka_gir": 0,
            "sol_gir": 0,
            "sağ_gir": 0,
            "ön_süpürgelik": 0,
            "arka_süpürgelik": 10,
            "sol_süpürgelik": 0,
            "sağ_süpürgelik": 0
        },
        "dik_köşe": {
            "dahil": False
        },
        "açılı_köşe": {
            "dahil": False
        }
    },
    "aventos": 0,
    "çekmece_var": False,
    "çekmece": False,
    "çekmece_sys": 0,
    "cam_kodu": 0,
    "çekmece_4": False,
    "üst_bşlk": 0.5,
    "kapak_arası": 0.3,
    "text1": "",
    "edit": True
}
